faiss_db:
  collection_name: "document_portal"

embeddings_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 10

llm_model:
  provider: "groq"
  model_name: "deepseek-llama-3.1-8b-instruct"
  temperature: 0
  max_tokens: 2048

logging:
  level: "info"
  log_file: "app.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - type: "file"
      filename: "app.log"
    - type: "console"